# Configuraci칩n de Netlify para AstroLab
[build]
  # Directorio donde est치 el proyecto
  base = "zodioteca"
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio donde se genera el build
  publish = "dist"

# Configuraci칩n de Node.js
[build.environment]
  NODE_VERSION = "18"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para media (audios de frecuencias)
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
